-- Migration: Add Training Plans and Planned Workouts
-- Date: 2025-10-27
-- Description: Adds training plan generation capability with planned workouts

-- Add athlete preferences columns
ALTER TABLE athletes 
ADD COLUMN IF NOT EXISTS training_goal TEXT,
ADD COLUMN IF NOT EXISTS weekly_hours_available INTEGER,
ADD COLUMN IF NOT EXISTS unavailable_days JSONB;

-- Create training_plans table
CREATE TABLE IF NOT EXISTS training_plans (
  id SERIAL PRIMARY KEY,
  athlete_id INTEGER NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  goal TEXT,
  status VARCHAR(20) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create planned_workouts table
CREATE TABLE IF NOT EXISTS planned_workouts (
  id SERIAL PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES training_plans(id) ON DELETE CASCADE,
  athlete_id INTEGER NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
  scheduled_date DATE NOT NULL,
  workout_type VARCHAR(100),
  description TEXT,
  duration_minutes INTEGER,
  target_tss INTEGER,
  intervals JSONB,
  status VARCHAR(20) DEFAULT 'planned',
  completed_ride_id INTEGER REFERENCES rides(id),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_training_plans_athlete ON training_plans(athlete_id);
CREATE INDEX IF NOT EXISTS idx_training_plans_dates ON training_plans(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_planned_workouts_athlete ON planned_workouts(athlete_id);
CREATE INDEX IF NOT EXISTS idx_planned_workouts_date ON planned_workouts(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_planned_workouts_status ON planned_workouts(status);

-- Add comments for documentation
COMMENT ON TABLE training_plans IS 'Multi-week training plans generated by AI';
COMMENT ON TABLE planned_workouts IS 'Individual workouts prescribed as part of a training plan';
COMMENT ON COLUMN athletes.training_goal IS 'Athlete''s current training objective';
COMMENT ON COLUMN athletes.weekly_hours_available IS 'Hours per week available for training';
COMMENT ON COLUMN athletes.unavailable_days IS 'JSON array of days athlete cannot train, e.g. ["monday", "friday"]';
COMMENT ON COLUMN planned_workouts.intervals IS 'JSONB array of interval structures with duration_seconds and power_ftp_percent';
COMMENT ON COLUMN planned_workouts.completed_ride_id IS 'Links to rides table when workout is completed';
